SELECT * FROM dentista;
SELECT * FROM CONSULTA;

CREATE TABLE DENTISTA(
	NOME VARCHAR(50),
	CFOID VARCHAR(10) PRIMARY KEY,
	CIRURGIAO BOOLEAN
)

CREATE TABLE CONSULTA(
	DATA DATE,
	CFOID_DENTISTA VARCHAR(10) REFERENCES DENTISTA(CFOID)
)